/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdio.h>


#define PORT00_BASE     (0xF003A000)
#define PORT00_OMR      (*(volatile unsigned int*)(PORT00_BASE + 0x04))
#define PORT00_IOCR4    (*(volatile unsigned int*)(PORT00_BASE + 0x14))
#define PORT00_IN       (*(volatile unsigned int*)(PORT00_BASE + 0x24))

#define PORT02_BASE     (0xF003A200)
#define PORT02_OMR      (*(volatile unsigned int*)(PORT02_BASE + 0x04))
#define PORT02_IOCR0    (*(volatile unsigned int*)(PORT02_BASE + 0X10))
#define PORT02_IOCR4    (*(volatile unsigned int*)(PORT02_BASE + 0x14))
#define PORT02_IN       (*(volatile unsigned int*)(PORT02_BASE + 0x24))

#define PORT10_BASE     (0xF003B000)
#define PORT10_OMR      (*(volatile unsigned int*)(PORT10_BASE + 0x04))
#define PORT10_IOCR0    (*(volatile unsigned int*)(PORT10_BASE + 0x10))
#define PORT10_IOCR4    (*(volatile unsigned int*)(PORT10_BASE + 0x14))
#define PORT10_IN       (*(volatile unsigned int*)(PORT10_BASE + 0x24))

#define P3              3
#define P4              4
#define P6              6
#define P7              7
#define PC1             11
#define PC2             19
#define PC3             27
#define PC4             3
#define PC5             11
#define PC6             19
#define PC7             27
#define PS1             1
#define PS2             2
#define PS3             3
#define PS4             4
#define PS5             5
#define PS6             6
#define PS7             7
#define PCL1            17
#define PCL2            18
#define PCL3            19
#define PCL4            20
#define PCL5            21
#define PCL6            22
#define PCL7            23

#define P0                  0
#define PC0                 3
#define PS0                 0
#define PCL0                16

void init_LED(void)
{
    // reset Port IOCR register
    PORT02_IOCR4 &= ~((0x1F) << PC7); //RGB LED RED
    PORT10_IOCR4 &= ~((0x1F) << PC5); //RGB LED GREEN
    PORT10_IOCR0 &= ~((0x1F) << PC3); //RGB LED BLUE
    PORT10_IOCR0 &= ~((0X1F) << PC1); // LED RED
    PORT10_IOCR0 &= ~((0X1F) << PC2); // LED BLUE

    // set Port as general purpose output (push-pull)
    PORT02_IOCR4 |= 0x11 << PC7;
    PORT10_IOCR4 |= 0x10 << PC5;
    PORT10_IOCR0 |= 0x10 << PC3;
    PORT10_IOCR0 |= 0X10 << PC1;
    PORT10_IOCR0 |= 0X11 << PC2;

}

void init_Switch(void)
{
    PORT02_IOCR0 &= ~((0X1F)<<PC0);
    PORT02_IOCR0 |= ((0X2)<<PC0);

}



// SCU Registers
#define SCU_BASE            (0xF0036000)
#define SCU_WDT_CPU0CON0    (*(volatile unsigned int*)(SCU_BASE + 0x100))
#define SCU_EICR0           (*(volatile unsigned int*)(SCU_BASE + 0x210))
#define SCU_EICR1           (*(volatile unsigned int*)(SCU_BASE + 0x214))
#define SCU_IGCR0           (*(volatile unsigned int*)(SCU_BASE + 0x22C))
#define SCU_EICR2           (*(volatile unsigned int*)(SCU_BASE + 0x218))

#define EXIS0               4
#define FEN0                8
#define REN0                9
#define EIEN0               11
#define INP0                12
#define IGP0                14

#define EXIS1               20
#define FEN1                24
#define REN1                25
#define EIEN1               27
#define INP1                28
#define IGP1                30

#define LCK                 1
#define ENDINIT             0

// SRC Registers
#define SRC_BASE            (0xF0038000)
#define SRC_CCU60_SR0       (*(volatile unsigned int*)(SRC_BASE + 0x420))
#define SRC_SCUERU0         (*(volatile unsigned int*)(SRC_BASE + 0xCD4))
#define SRC_SCUERU1         (*(volatile unsigned int*)(SRC_BASE + 0xCD8))

#define TOS                 11
#define SRE                 10
#define SRPN                0



void init_ERU(void)
{
    // ERU setting
    SCU_EICR1 &= ~((0x07) << EXIS0);
    SCU_EICR1 |=  ((0x02) << EXIS0);     // ERS2 - Input 2
    SCU_EICR1 &= ~((0x07) << EXIS1);
    SCU_EICR1 |=  ((0x02) << EXIS1);

    SCU_EICR1 |=  ((0x01) << FEN0);      // Enable falling edge
    SCU_EICR1 |=  ((0x01) << REN0);      // Enable rising edge
    SCU_EICR1 |=  (1 << FEN1);
    //SCU_EICR1 |=  (1 << REN1);

    SCU_EICR1 |=  ((0x01) << EIEN0);     // External Interrupt Enable
    SCU_EICR1 |=  ((0x01) << EIEN1);

    SCU_EICR1 &= ~((0x07) << INP0);      // Input Node Pointer from OGU0
    SCU_EICR1 &= ~((0x07) << INP1);
    SCU_EICR1 |=  ((0x01) << INP1);


    SCU_IGCR0 &= ~((0x03) << IGP0);
    SCU_IGCR0 |=  ((0x01) << IGP0);      // Interrupt Gatting Pattern 0

    SCU_IGCR0 &= ~((0x3) << IGP1);
    SCU_IGCR0 |=  ((0x1) << IGP1);


    // SRC Interrupt setting
    SRC_SCUERU0 &= ~((0xFF) << SRPN);
    SRC_SCUERU0 |=  ((0x0A) << SRPN);

    SRC_SCUERU0 &= ~((0x03) << TOS);
    SRC_SCUERU0 |=  ((0x01) << SRE);

    SRC_SCUERU1 &= ~((0xFF) << SRPN);
    SRC_SCUERU1 |=  ((0x0C) << SRPN);

    SRC_SCUERU1 &= ~((0x3) << TOS);
    SRC_SCUERU1 |=  (1 << SRE);
}

// CCU6 Registers
#define CCU60_BASE          (0xF0002A00)
#define CCU60_CLC           (*(volatile unsigned int*)(CCU60_BASE + 0x00))
#define CCU60_T12           (*(volatile unsigned int*)(CCU60_BASE + 0x20))
#define CCU60_T12PR         (*(volatile unsigned int*)(CCU60_BASE + 0x24))
#define CCU60_TCTR0         (*(volatile unsigned int*)(CCU60_BASE + 0x70))
#define CCU60_TCTR2         (*(volatile unsigned int*)(CCU60_BASE + 0x74))
#define CCU60_TCTR4         (*(volatile unsigned int*)(CCU60_BASE + 0x78))
#define CCU60_INP           (*(volatile unsigned int*)(CCU60_BASE + 0xAC))
#define CCU60_IEN           (*(volatile unsigned int*)(CCU60_BASE + 0xB0))

#define CCU61_BASE          (0xF0002B00)
#define CCU61_CLC           (*(volatile unsigned int*)(CCU61_BASE + 0x00))
#define CCU61_T12           (*(volatile unsigned int*)(CCU61_BASE + 0x20))
#define CCU61_T12PR         (*(volatile unsigned int*)(CCU61_BASE + 0x24))
#define CCU61_TCTR0         (*(volatile unsigned int*)(CCU61_BASE + 0x70))
#define CCU61_TCTR2         (*(volatile unsigned int*)(CCU61_BASE + 0x74))
#define CCU61_TCTR4         (*(volatile unsigned int*)(CCU61_BASE + 0x78))
#define CCU61_INP           (*(volatile unsigned int*)(CCU61_BASE + 0xAC))
#define CCU61_IEN           (*(volatile unsigned int*)(CCU61_BASE + 0xB0))


#define DISS                1
#define DISR                0
#define CTM                 7
#define T12PRE              3
#define T12CLK              0
#define T12STR              6
#define INPT12              10
#define ENT12PM             7
#define T12SSC              0
#define T12RR               0
#define T12RS               1
#define T12RES              2

#define PWM_FREQ        6250000

volatile uint32 range;
volatile uint8 range_valid_flag = 0;

void init_USonic(void)
{
    PORT02_IOCR4 &= ~(0x1F << PC6);     // reset PORT02_IOCR4 PC6
    PORT00_IOCR4 &= ~(0x1F << PC4);     // reset PORT00_IOCR4 PC4

    PORT00_IOCR4 |= 0x01 << PC4;        // set P00.4 general input (pull-down connected) [Echo]
    PORT02_IOCR4 |= 0x10 << PC6;        // set P02.6 push-pull general output            [Trig]

    PORT02_OMR |= ((0x01) << PCL6);
}

void init_CCU60(void)
{
    // Password Access to unlock SCU_WDTSCON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);    // wait until unlocked

    // Modify Access to clear ENDINIT
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);    // wait until locked

    CCU60_CLC &= ~(1 << DISR);                      // enable CCU

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);    // wait until unlocked

    // Modify Access to set ENDINIT
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);    // wait until locked

    // CCU60 T12 configurations
    while((CCU60_CLC & (1 << DISS)) != 0);          // wait until CCU60 module enabled


    CCU60_TCTR0 &= ~((0x07) << T12CLK);     // f_T12 = f_CCU6 / prescaler
    CCU60_TCTR0 |=  ((0x02) << T12CLK);     // f_CCU6 = 100 MHz, prescaler = 4

    CCU60_TCTR0 &= ~((0x01) << CTM);        // T12 auto reset when period match (PM) occur

    CCU60_T12PR = 250 - 1;                  // PM interrupt freq. = f_T12 / (T12PR + 1)
    CCU60_TCTR4 |= ((0x01) << T12STR);      // load T12PR from shadow register

    CCU60_TCTR2 =  ((0x01) << T12SSC);      // Single Shot Control

    CCU60_T12 = 0;                          // clear T12 counter register


    // CCU60 T12 PM interrupt setting
    CCU60_INP &= ~((0x03) << INPT12);       // service request output SR0 selected
    CCU60_IEN |=  ((0x01) << ENT12PM);      // enable T12 PM interrupt


    // SRC setting for CCU60
    SRC_CCU60_SR0 &= ~((0xFF) << SRPN);
    SRC_CCU60_SR0 |=  ((0x0B) << SRPN);     // set priority 0x0B

    SRC_CCU60_SR0 &= ~((0x03) << TOS);      // CPU0 service T12 PM interrupt
    SRC_CCU60_SR0 |=  ((0x01) << SRE);      // SR0 enabled
}

void usonicTrigger(void)
{
    // start of 10us Trigger Pulse
    // GPIO P02.6 --> HIGH
    PORT02_OMR |= ((0x01) << PS6);
    range_valid_flag = 0;
    CCU60_TCTR4 = 0x1 << T12RS;         // T12 start counting
}

__interrupt(0x0B) __vector_table(0)
void CCU60_T12_ISR(void)
{
    // end of 10us Trig
    // GPIO P02.6 --> LOW
    PORT02_OMR |= ((0x01) << PCL6);
}

void init_CCU61(void)
{

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);    // wait until unlocked

    // Modify Access to clear ENDINIT
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);    // wait until locked

    CCU61_CLC &= ~(1 << DISR);                      // enable CCU

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);    // wait until unlocked

    // Modify Access to set ENDINIT
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);    // wait until locked

    // CCU60 T12 configurations
    while((CCU61_CLC & (1 << DISS)) != 0);          // wait until CCU60 module enabled



    CCU61_TCTR0 &= ~(0x7 << T12CLK);        // f_T12 = f_CCU6 / prescaler = 25 MHz
    CCU61_TCTR0 |= 0x2 << T12CLK;           // f_CCU6 = 100 MHz, prescaler = 4

    CCU61_TCTR0 |= 0x1 << T12PRE;           // f_T12 = f_CCU6 / 256 = 97,656 Hz


    CCU61_T12PR = 100000 -1;                // PM interrupt freq. = f_T12 / (T12PR + 1)
    CCU61_TCTR4 |= 0x1 << T12STR;           // load T12PR from shadow register

    CCU61_T12 = 0;                          // clear T12 counter register
}

__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
    if( (PORT00_IN & (0x1 << P4)) != 0 )    // rising edge of echo
    {
        //                    _________
        //        echo ______|
        //                   ^
        CCU61_TCTR4 = 0x01 << T12RS;        // start CCU61 T12 counter
    }
    else                                    // falling edge of echo
    {
        //             ______
        //        echo       |______
        //                   ^
        CCU61_TCTR4 = ((0x01) << T12RR);    // stop CCU61 T12 counter

        // (1 / t_freq) * counter * 1000000 / 58  =  centimeter
        //range = ((CCU61_T12 * 1000000) / 48828) / 58;
        range = ((CCU61_T12 * 1000000) / 97656) / 58;
        if (range < 500)
            range_valid_flag = 1;

        CCU61_TCTR4 |=  ((0x01) << T12RES);  // reset CCU61 T12 counter
    }
}

//GTM Registers
//GTM CMU
#define GTM_BASE            (0xF0100000)
#define GTM_CMU_CLK_EN      (*(volatile unsigned int*)(GTM_BASE + 0x00300))
#define GTM_CMU_FXCLK_CTRL  (*(volatile unsigned int*)(GTM_BASE + 0x00344))

#define EN_FXCLK            22
#define FXCLK_SEL           0

//GTM TOM0
#define GTM_TOM0_TGC0_GLB_CTRL        (*(volatile unsigned int*)(GTM_BASE + 0x08030))
#define GTM_TOM0_TGC0_ENDIS_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08070))
#define GTM_TOM0_TGC0_OUTEN_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08078))
#define GTM_TOM0_TGC0_FUPD_CTRL       (*(volatile unsigned int*)(GTM_BASE + 0x08038))

#define GTM_TOM0_CH1_CTRL             (*(volatile unsigned int*)(GTM_BASE + 0x08040))
#define GTM_TOM0_CH1_SR0              (*(volatile unsigned int*)(GTM_BASE + 0x08044))
#define GTM_TOM0_CH1_SR1              (*(volatile unsigned int*)(GTM_BASE + 0x08048))

#define GTM_TOM0_CH2_CTRL             (*(volatile unsigned int*)(GTM_BASE + 0x08080))
#define GTM_TOM0_CH2_SR0              (*(volatile unsigned int*)(GTM_BASE + 0x08084))
#define GTM_TOM0_CH2_SR1              (*(volatile unsigned int*)(GTM_BASE + 0x08088))

#define GTM_TOM0_TGC1_GLB_CTRL        (*(volatile unsigned int*)(GTM_BASE + 0x08230))
#define GTM_TOM0_TGC1_ENDIS_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08270))
#define GTM_TOM0_TGC1_OUTEN_CTRL      (*(volatile unsigned int*)(GTM_BASE + 0x08278))
#define GTM_TOM0_TGC1_FUPD_CTRL       (*(volatile unsigned int*)(GTM_BASE + 0x08238))

//FOR RGB LED RED
#define GTM_TOM0_CH15_CTRL            (*(volatile unsigned int*)(GTM_BASE + 0x083C0))
#define GTM_TOM0_CH15_SR0             (*(volatile unsigned int*)(GTM_BASE + 0x083C4))
#define GTM_TOM0_CH15_SR1             (*(volatile unsigned int*)(GTM_BASE + 0x083C8))
//FOR BUZZER
#define GTM_TOM0_CH11_CTRL            (*(volatile unsigned int*)(GTM_BASE + 0x082C0))
#define GTM_TOM0_CH11_SR0             (*(volatile unsigned int*)(GTM_BASE + 0x082C4))
#define GTM_TOM0_CH11_SR1             (*(volatile unsigned int*)(GTM_BASE + 0x082C8))
//FOR MOTOR
#define GTM_TOM0_CH9_CTRL           (*(volatile unsigned int*)(GTM_BASE + 0x08240))
#define GTM_TOM0_CH9_SR0            (*(volatile unsigned int*)(GTM_BASE + 0x08244))
#define GTM_TOM0_CH9_SR1            (*(volatile unsigned int*)(GTM_BASE + 0x08248))



#define CLK_SRC_SR          12
#define SL                  11
#define HOST_TRIG           0

#define UPEN_CTRL1          18
#define UPEN_CTRL2          20
#define UPEN_CTRL3          22
#define UPEN_CTRL7          30

#define ENDIS_CTRL1         2
#define ENDIS_CTRL2         4
#define ENDIS_CTRL3         6
#define ENDIS_CTRL7         14

#define OUTEN_CTRL1         2
#define OUTEN_CTRL2         4
#define OUTEN_CTRL3         6
#define OUTEN_CTRL7         14

#define RSTCN0_CH1          18
#define RSTCN0_CH2          20
#define RSTCN0_CH3          22
#define RSTCN0_CH15         30

#define FUPD_CTRL1          2
#define FUPD_CTRL2          4
#define FUPD_CTRL3          6
#define FUPD_CTRL7          14

//GTM
#define GTM_CLC            (*(volatile unsigned int*)(GTM_BASE + 0x9FD00))
#define GTM_TOUTSEL6       (*(volatile unsigned int*)(GTM_BASE + 0x9FD48))
#define GTM_TOUTSEL1       (*(volatile unsigned int*)(GTM_BASE + 0x9FD34))
#define GTM_TOUTSEL0       (*(volatile unsigned int*)(GTM_BASE + 0x9FD30))

#define DISS               1
#define DISR               0
#define SEL3               6
#define SEL7               14
#define SEL8               16
#define SEL1               2
#define SEL11              22


#define UPEN_CTRL1          18
#define UPEN_CTRL2          20
#define UPEN_CTRL3          22
#define HOST_TRIG           0
#define ENDIS_CTRL1         2
#define ENDIS_CTRL2         4
#define ENDIS_CTRL3         6
#define OUTEN_CTRL1         2
#define OUTEN_CTRL2         4
#define OUTEN_CTRL3         6
#define RSTCN0_CH1          18
#define RSTCN0_CH2          20
#define RSTCN0_CH3          22
#define FUPD_CTRL1          2
#define FUPD_CTRL2          4
#define FUPD_CTRL3          6
#define CLK_SRC_SR          12
#define SL                  11

void init_Buzzer(void)
{
    PORT02_IOCR0 &= ~((0x1F) << PC3);           // PORT02.3 : Alternate output function 1 (push-pull)
    PORT02_IOCR0 |= ((0x11) << PC3);            // PORT02.3 : GTM_TOUT3
}


void init_GTM_TOM0_PWM(void)
{
    /* Passwaord Access to unlock WDTSCON0 */
       SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) &~ (1 << LCK)) | (1 << ENDINIT);
       while ((SCU_WDT_CPU0CON0 & (1 << LCK))!=0);

       // Modify Access to clear ENDINIT bit
       SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~ (1 << ENDINIT);
       while ((SCU_WDT_CPU0CON0 & (1 << LCK))==0);

       GTM_CLC &= ~(1 << DISR);

    /* Passwaord Access to unlock WDTSCON0 */
       SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) &~ (1 << LCK)) | (1 << ENDINIT);
       while ((SCU_WDT_CPU0CON0 & (1 << LCK))!=0);

    // Modify Access to clear ENDINIT bit
       SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
       while ((SCU_WDT_CPU0CON0 & (1 << LCK))==0);

       while ((GTM_CLC & (1 <<DISS)) != 0);

      //GTM Clock Setting
      GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL);

      GTM_CMU_CLK_EN &= ~((0x3) << EN_FXCLK);
      GTM_CMU_CLK_EN |=   ((0x2) << EN_FXCLK);

      /* TOM0 채널15 for RGB LED RED */
      GTM_TOM0_TGC1_GLB_CTRL &= ~((0x3) << UPEN_CTRL7);
      GTM_TOM0_TGC1_GLB_CTRL |=   ((0x2) << UPEN_CTRL7);

      GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << FUPD_CTRL7);
      GTM_TOM0_TGC1_FUPD_CTRL |=   ((0x2) << FUPD_CTRL7);
      GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << RSTCN0_CH15);
      GTM_TOM0_TGC1_FUPD_CTRL |=   ((0x2) << RSTCN0_CH15);

      GTM_TOM0_TGC1_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL7);
      GTM_TOM0_TGC1_ENDIS_CTRL |=   ((0x2) << ENDIS_CTRL7);
      GTM_TOM0_TGC1_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL7);
      GTM_TOM0_TGC1_OUTEN_CTRL |=   ((0x2) << OUTEN_CTRL7);

      GTM_TOM0_CH15_CTRL |=  (1 << SL);
      GTM_TOM0_CH15_CTRL &= ~((0x7) << CLK_SRC_SR);
      GTM_TOM0_CH15_CTRL |=  (1     << CLK_SRC_SR);
      GTM_TOM0_CH15_SR0 = 12500 - 1;
      GTM_TOM0_CH15_SR1 = 0;

      GTM_TOUTSEL1 &= ~((0x3) << SEL7); // TOUT7 TOM0 CH15

      /*TMO 채널11 for buzzer*/
      GTM_TOM0_TGC1_GLB_CTRL &= ~((0x3) << UPEN_CTRL3);   // TOM0 channel 11 enable update of
      GTM_TOM0_TGC1_GLB_CTRL |= ((0x2) << UPEN_CTRL3);    // register CM0, CM1, CLK_SRC

      GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << FUPD_CTRL3);  // Enable force update of TOM0 channel 11
      GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << FUPD_CTRL3);
      GTM_TOM0_TGC1_FUPD_CTRL &= ~((0x3) << RSTCN0_CH3);  // Reset CN0 of TOM0 channel 11 on force update
      GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << RSTCN0_CH3);

      GTM_TOM0_TGC1_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL3); // Enable channel 11 on an update trigger
      GTM_TOM0_TGC1_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL3);
      GTM_TOM0_TGC1_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL3); // Enable channel 11 output on an update trigger
      GTM_TOM0_TGC1_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL3);

      GTM_TOM0_CH11_CTRL |= (1 << SL);                    // High signal level for duty cycle
      GTM_TOM0_CH11_CTRL &= ~((0x7) << CLK_SRC_SR);       // Clock source : CMU_FXCLK(1) = 6250 kHz
      GTM_TOM0_CH11_CTRL |= (1 << CLK_SRC_SR);
      GTM_TOM0_CH11_SR0 = 12500 - 1;                      // PWM freq. = 6250 kHz / 12500 = 500 Hz
      GTM_TOM0_CH11_SR1 = 0;                              // Duty cycle = 0

      GTM_TOUTSEL0 &= ~((0x3) << SEL3);                   // TOUT3 : TOM0 channel 11

      //MOTOR

      GTM_TOM0_TGC1_GLB_CTRL |= ((0x02) << UPEN_CTRL1);
         GTM_TOM0_TGC1_ENDIS_CTRL |= ((0x02) << ENDIS_CTRL1);
         GTM_TOM0_TGC1_OUTEN_CTRL |= ((0x02) << OUTEN_CTRL1);

         GTM_TOM0_CH9_CTRL |= ((0x01) << SL);
         GTM_TOM0_CH9_CTRL |= ((0x01) << CLK_SRC_SR);

         GTM_TOM0_CH9_SR0 = 12500 - 1;
         GTM_TOM0_CH9_SR1 = 0;
         GTM_TOUTSEL0 &= ~((0x03) << SEL1);


         // LED BLUE
         GTM_TOM0_TGC0_GLB_CTRL &= ~((0x3) << UPEN_CTRL2);
                       GTM_TOM0_TGC0_GLB_CTRL |= ((0x2) << UPEN_CTRL2);

                       GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << FUPD_CTRL2);
                       GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << FUPD_CTRL2);
                       GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << RSTCN0_CH2);
                       GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << RSTCN0_CH2);

                       GTM_TOM0_TGC0_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL2);
                       GTM_TOM0_TGC0_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL2);
                       GTM_TOM0_TGC0_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL2);
                       GTM_TOM0_TGC0_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL2);

                GTM_TOM0_CH2_CTRL |= (1<<SL);

                GTM_TOM0_CH2_CTRL &= ~((0x7)<<CLK_SRC_SR);
                GTM_TOM0_CH2_CTRL |= (1<<CLK_SRC_SR);
                GTM_TOM0_CH2_SR0 = 12500-1;

                GTM_TOM0_CH2_SR1 = 0;

                GTM_TOUTSEL6 &= ~((0x3)<<SEL8);

                GTM_TOM0_TGC0_GLB_CTRL |= (1<< HOST_TRIG);

      GTM_TOM0_TGC1_GLB_CTRL |= (1 << HOST_TRIG);         // Trigger request signal to update

}

void initMotor(void)
{
    PORT10_IOCR0 &= ~(0x1F << PC1);
    PORT02_IOCR0 &= ~(0x1F << PC1);
   PORT02_IOCR4 &= ~(0x1F << PC7);

    PORT10_IOCR0 |= (0x10 << PC1);  // Set D12 to OUTPUT (DIRA)
    PORT02_IOCR0 |= (0x11 << PC1);  // Set D3 to PWM OUTPUT (PWMA)
    PORT02_IOCR4 |= (0x10 << PC7);  // Set D9 to OUTPUT (BRAKE_A)
}

//  VADC Register
#define VADC_BASE         (0xF0020000)
#define VADC_CLC          (*(volatile unsigned int*)(VADC_BASE + 0x000))
#define VADC_GBLOCFG      (*(volatile unsigned int*)(VADC_BASE + 0x080))
#define VADC_G4ARBCFG     (*(volatile unsigned int*)(VADC_BASE + 0x1480))
#define VADC_G4ARBPR      (*(volatile unsigned int*)(VADC_BASE + 0x1484))
#define VADC_G4ICLASS0    (*(volatile unsigned int*)(VADC_BASE + 0x14A0))
#define VADC_G4QMR0       (*(volatile unsigned int*)(VADC_BASE + 0x1504))
#define VADC_G4QINR0      (*(volatile unsigned int*)(VADC_BASE + 0x1510))
#define VADC_G4CHCTR7     (*(volatile unsigned int*)(VADC_BASE + 0x161C))
#define VADC_G4RES1       (*(volatile unsigned int*)(VADC_BASE + 0x1704))

#define DISS              1
#define DISR              0
#define ANONC             0
#define ASEN0             24
#define CSM0              3
#define PRIO0             0
#define CMS               8
#define STCS              0
#define FLUSH             10
#define TREV              9
#define ENGT              0
#define RF                5
#define REQCHNR           0
#define RESPOS            21
#define RESREG            16
#define ICLSEL            0
#define VF                31
#define RESULT            0


void init_VADC(void)
{
    /* Passwaord Access to unlock WDTSCON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) &~ (1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK))!=0);

    // Modify Access to clear ENDINIT bit
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~ (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK))==0);

    VADC_CLC &= ~(1<<DISR);

    /* Passwaord Access to unlock WDTSCON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) &~ (1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK))!=0);

    // Modify Access to clear ENDINIT bit
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK))==0);

    while ((VADC_CLC & (1<< DISS)) != 0);

    VADC_G4ARBPR  |=   ((0x3) << PRIO0);
    VADC_G4ARBPR  &= ~ (1     << CSM0);
    VADC_G4ARBPR  |=   (1     << ASEN0);

    VADC_G4QMR0   &= ~ ((0x3) << ENGT);
    VADC_G4QMR0   |=   ((0x1) << ENGT);

    VADC_G4QMR0   |=   (1     << FLUSH);

    VADC_G4ARBCFG |=   ((0x3) << ANONC);

    VADC_G4ICLASS0&= ~ ((0x7) << CMS);

    // VADC Group 4 Channel 7 Setting
    VADC_G4CHCTR7 |=   (1     << RESPOS);
    VADC_G4CHCTR7 &= ~ ((0xF) << RESREG);
    VADC_G4CHCTR7 |=   (1     << RESREG);
    VADC_G4CHCTR7 &= ~ ((0x3) << ICLSEL);
}

void VADC_startConversion(void)
{
    VADC_G4QINR0 &= ~(0x1F);
    VADC_G4QINR0 |=  (0x07);

    VADC_G4QINR0 &= ~(1 <<  RF);

    VADC_G4QMR0  |=  (1 <<  TREV);
}

unsigned int VADC_readResult(void)
{
    unsigned int result;

    while((VADC_G4RES1 & (1 << VF)) == 0 );
    result = (VADC_G4RES1 & ((0xFFFF) << RESULT));
    return result;
}


IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define PWM_FREQ        6250000
int num_tones = 8;
int tones[] = {261, 277, 294, 311, 330, 349, 370, 392};
volatile int cycle;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    init_ERU();
    init_CCU60();
    init_CCU61();
    init_LED();
    init_USonic();
    init_GTM_TOM0_PWM();
    init_Buzzer();
    init_VADC();
    initMotor();
    unsigned int adcresult;

    while(1)
    {
        VADC_startConversion();
        adcresult = VADC_readResult();

        if(adcresult >= 3000)
        {
          //* 버그 수정 위한 추가 *//
          GTM_TOM0_CH11_SR1 = 0;
          GTM_TOM0_CH2_SR1 = 0;
          //* 버그 수정 위한 추가 *//

          GTM_TOM0_CH9_SR1 = (12500*(adcresult-3000))/(4096-3000);

          PORT10_OMR |= ((0x01) << PS3);
          PORT10_OMR |= ((0x01) << PCL5);
          PORT10_OMR |= ((0x01) << PCL1);
        }

        else if(adcresult >= 2500)
        {
          //* 버그 수정 위한 추가 *//
          GTM_TOM0_CH11_SR1 = 0;
          GTM_TOM0_CH2_SR1 = 0;
          GTM_TOM0_CH9_SR1 = 0;
          //* 버그 수정 위한 추가 *//
          PORT10_OMR |= ((0x01) << PS5);
          PORT10_OMR |= ((0x01) << PCL3);
          PORT10_OMR |= ((0x01) << PCL1);
        }

        else if(adcresult >=500)
        {


          PORT10_OMR |= ((0x01) << PS1);      // Set DIRA to BACK
          PORT10_OMR |= ((0x01) << PCL5);
          PORT10_OMR |= ((0x01) << PCL3);


          usonicTrigger();

            for (uint8 i = 0; i < 4; i++)
                for(uint32 j = 0; j < 10000000; j++);

                if (range_valid_flag > 0)
                {
                        if( range >= 30 ) // scenario_1
                        {
                            GTM_TOM0_CH11_SR1 = 0;
                            GTM_TOM0_CH2_SR1 =0;
                            GTM_TOM0_CH9_SR1 = (12500*(adcresult-500))/(3096);

                        }
                        else if( range >= 20 ) // scenario_2 /
                        {
                            GTM_TOM0_CH11_SR0 = 23946;          //ch11 주파수 for buzzer (낮은 도음)
                            GTM_TOM0_CH11_SR1 = 23946/2;
                            GTM_TOM0_CH2_SR1 = 1250-1;
                            GTM_TOM0_CH9_SR1 = (12500*(adcresult-500))/(3096);

                        }
                        else if( range >= 10) // scenario_3
                        {
                            GTM_TOM0_CH11_SR0 = 18939;          //ch11 주파수 for buzzer (솔음)
                            GTM_TOM0_CH11_SR1 = 18939/2;
                            GTM_TOM0_CH2_SR1 = 5250-1;
                            GTM_TOM0_CH9_SR1 = 2000;

                        }
                        else //  scenario_4
                        {
                            GTM_TOM0_CH11_SR0 = 15943;          //ch11 주파수 for buzzer (높은 도음)
                            GTM_TOM0_CH11_SR1 = 15943/2;
                            GTM_TOM0_CH2_SR1 = 12500-1;        //RGB LED RED 100% DUTY
                            GTM_TOM0_CH9_SR1 =0;

                        }
                   }
            }
        else
        {
            GTM_TOM0_CH11_SR1 = 0;
            GTM_TOM0_CH2_SR1 = 0;
            GTM_TOM0_CH9_SR1 =0;
            //* 버그 수정 위한 추가 *//

            PORT10_OMR |= ((0x01) << PS3);
            PORT10_OMR |= ((0x01) << PS5);
            PORT10_OMR |= ((0x01) << PCL1);

            //PORT02_OMR |= ((1<< PCL7)| (1<<PS7));
        }
    }
    return (1);
}

__interrupt(0x0C) __vector_table(0) // P단 스위치 (D2) 인터럽트
void ERU1_ISR(void)
{

    CCU60_IEN ^= (1<< ENT12PM); // CCU60 disable

      // PORT10_OMR |= ((1<<PCL2)|(1<<PS2)); // LED BLUE TOGGLE

       //* 버그 수정 위한 추가 *//
       GTM_TOM0_CH11_SR1 = 0;
       GTM_TOM0_CH15_SR1 = 0;
       GTM_TOM0_CH2_SR1 = 0;

       //* 버그 수정 위한 추가 *//

       PORT02_IOCR0 ^= ((0x11) << PC3); // BUZZER TOGGLE
      //PORT02_IOCR4 ^= ((0x11) << PC7); // RGB LED RED TOGGLE
       PORT10_IOCR4 ^= ((0x10) << PC5); // RGB LED GREEN TOGGLE
       PORT10_IOCR0 ^= ((0x10) << PC3); // RGB LED BLUE TOGGLE
       PORT10_IOCR0 ^= ((0x10) << PC1); // LED RED TOGGLE
       PORT10_IOCR0 ^= ((0x11) << PC2); // LED BLUE TOGGLE
       PORT02_OMR |= ((1<< PCL7)| (1<<PS7));     // BRAKE TOGGLE



}
